#!/usr/bin/env ruby

require "#{File.dirname __FILE__}/install_scripts/colorize"
require "#{File.dirname __FILE__}/install_scripts/platform"

puts 'Cloning powerlevel9k from GitHub (bhilburn/powerlevel9k)...'.blue
system "git clone --depth 1 https://github.com/bhilburn/powerlevel9k '#{POWERLEVEL9K_DIR}'"
puts 'Done.'.blue

unless File.exist? "#{THEMES_DIR}/powerlevel9k.zsh-theme"
  puts 'Symlinking powerlevel9k theme file...'.blue
  system "ln -s '#{POWERLEVEL9K_DIR}/powerlevel9k.zsh-theme' '#{THEMES_DIR}/powerlevel9k.zsh-theme'"
  puts 'Done.'.blue
end

fonts_dir = case OS.which?
when :linux
  "/usr/share/fonts"
when :macos
  "~/.fonts"
when :windows
  "C:\Windows\Fonts"
end

unless File.exist? "#{fonts_dir}/Hack Regular Nerd Font Complete.ttf"
  puts 'Installing Hack Nerd Font (ryanoasis/nerd-fonts)...'.blue
  case OS.which?
  when :windows
    system "./install.ps1 Hack"
  else
    system "./install.sh Hack"
  end
  puts 'Done.'.blue
else
  STDERR.puts 'Hack Nerd Font is already installed.'.green
end
